# Generated by Django 5.2 on 2025-04-15 02:33

import django.db.models.deletion
import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolioapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.FloatField(default=time.time)),
                ("total_value", models.FloatField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="portfolioapp.portfolio",
                    ),
                ),
            ],
        ),
    ]
