# Generated by Django 5.2 on 2025-04-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='name',
            field=models.CharField(default='Untitled Session', max_length=100, unique=True),
        ),
    ]