# Generated by Django 5.2 on 2025-04-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_merge_0002_add_name_0002_tradelog_reasoning'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='share_price',
            new_name='share_price_at_purchase',
        ),
        migrations.RenameField(
            model_name='tradelog',
            old_name='price',
            new_name='share_price',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
