# Generated by Django 5.2 on 2025-04-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_rename_share_price_position_share_price_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationsession',
            name='simulated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
